SELECT DISTINCT ?Person_1 (GROUP_CONCAT(DISTINCT ?Person_1_alias; SEPARATOR = "; ") AS ?Person_1_aliass) ?Person_1_code ?Country_1 ?Country_1_label WHERE {
  ?Person_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.
  ?Person_1 <http://example.com/Person_country> ?Country_1.
  ?Country_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Country>.
  ?Country_1 <http://example.com/Country_label> ?Country_1_label.
  ?Person_1 <http://example.com/Person_code> ?Person_1_code.
  OPTIONAL { ?Person_1 <http://example.com/Person_alias> ?Person_1_alias. }
}
GROUP BY ?Person_1 ?Person_1_code ?Country_1 ?Country_1_label
