SELECT DISTINCT ?Person_1 ?Person_2 ?Organization_1 ?Person_3 ?Country_1 ?Country_1_label ?Organization_1_label WHERE {
  ?Person_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.
  ?Person_1 <http://example.com/Person_knows> ?Person_2.
  ?Person_2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.
  ?Person_2 <http://example.com/Person_memberOf> ?Organization_1.
  ?Organization_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Organization>.
  OPTIONAL {
    ?Organization_1 <http://example.com/Organization_name> ?Organization_1_label.
    FILTER((LANG(?Organization_1_label)) = "en")
  }
  ?Organization_1 <http://example.com/Organization_member> ?Person_3.
  ?Person_3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.
  ?Person_3 <http://example.com/Person_country> ?Country_1.
  ?Country_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Country>.
  OPTIONAL { ?Country_1 <http://example.com/Country_label> ?Country_1_label. }
  ?Country_1 <http://example.com/Country_continent> <http://example.com/continent/EU>.
}
