SELECT DISTINCT ?Person_1 ?Text_1 ?Text_2 WHERE {
  ?Person_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.
  ?Person_1 <http://example.com/Person_title> ?Text_1.
  FILTER((LANG(?Text_1)) = "fr")
  FILTER(REGEX(STR(?Text_1), "doctor", "i"))
  OPTIONAL {
    ?Person_1 <http://example.com/Person_title> ?Text_2.
    FILTER((LANG(?Text_2)) = "fr")
  }
}
