PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#SELECT DISTINCT ?class  (COUNT(?s) AS ?instanceTotal)
CONSTRUCT {
    ?class rdf:type owl:Class ;
           rdfs:subClassOf <http://data.sparna.fr/ontologies/sparnatural-config-core#SparnaturalClass> .
}
WHERE {
    ?s a ?class .
    FILTER(?class != rdf:List &&
        ?class != owl:SymmetricProperty	&&
        ?class != owl:TransitiveProperty	&&
        ?class != rdfs:Class	&&
        ?class != rdfs:Datatype &&
        ?class != rdf:Property &&
        ?class != rdfs:ContainerMembershipProperty)
}
ORDER BY ?class