PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

#SELECT DISTINCT ?class ?label1
CONSTRUCT {?class rdfs:label ?label1}
WHERE {
    ?s rdf:type ?class .
    OPTIONAL 
    {?class rdfs:label ?label . }
    BIND(IF(BOUND(?label),?label,STRAFTER(str(?class),"#")) AS ?label1) . 
    FILTER((?class != rdf:List &&
            ?class != owl:SymmetricProperty	&&
            ?class != owl:TransitiveProperty	&&
            ?class != rdfs:Class	&&
            ?class != rdfs:Datatype &&
            ?class != rdf:Property &&
            ?class != rdfs:ContainerMembershipProperty))
} 
ORDER BY ?class