import * as fs from 'fs';
import * as path from 'path';
import { Parser } from '@traqula/parser-sparql-1-1';
import { JsonV13SparqlTranslator } from '../../sparnatural/generators/sparql/fromjsonv13/JsonV13SparqlTranslator';
import { SparqlGeneratorV13 } from '../../sparnatural/generators/sparql/fromjsonv13/SparqlGeneratorV13';
import { SparnaturalQuery } from '../../sparnatural/SparnaturalQueryIfc-v13';
import { SparnaturalSpecificationFactory } from '../../sparnatural/spec-providers/SparnaturalSpecificationFactory';

async function buildSpecProviderFromConfig(configTtl: string, language = 'en') {
  const factory = new SparnaturalSpecificationFactory();
  return await new Promise<any>((resolve, reject) => {
    try {
      factory.build(configTtl, language, undefined, (provider: any) => resolve(provider));
    } catch (e) {
      reject(e);
    }
  });
}

function loadTestCases(baseDir: string) {
  const entries = fs.readdirSync(baseDir, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory())
    .map((dir) => path.join(baseDir, dir.name));
}

describe('JsonV13SparqlTranslator directory-driven tests', () => {
  const baseDir = path.join(__dirname, 'cases');
  const generator = new SparqlGeneratorV13();
  const parser = new Parser();
  // config shared by the test cases that don't provide their own config.ttl
  const sharedConfigPath = path.join(baseDir, 'config.ttl');

  if (!fs.existsSync(baseDir)) {
    it('has a cases directory', () => {
      expect(fs.existsSync(baseDir)).toBe(true);
    });
    return;
  }

  const caseDirs = loadTestCases(baseDir);

  if (caseDirs.length === 0) {
    it('has at least one test case directory', () => {
      expect(caseDirs.length).toBeGreaterThan(0);
    });
    return;
  }

  for (const casedir of caseDirs) {
    const label = path.basename(casedir);

    it(`translates case: ${label}`, async () => {
      const queryPath = path.join(casedir, 'query.json');
      const caseConfigPath = path.join(casedir, 'config.ttl');
      const configPath = fs.existsSync(caseConfigPath) ? caseConfigPath : sharedConfigPath;
      const expectedPath = path.join(casedir, 'expected.rq');
      // optional settings, overriding the default ones
      const settingsPath = path.join(casedir, 'settings.json');

      expect(fs.existsSync(queryPath)).toBe(true);
      expect(fs.existsSync(configPath)).toBe(true);
      expect(fs.existsSync(expectedPath)).toBe(true);

      const queryJson = JSON.parse(fs.readFileSync(queryPath, 'utf-8')) as SparnaturalQuery;
      const configTtl = fs.readFileSync(configPath, 'utf-8');
      const expectedRaw = fs.readFileSync(expectedPath, 'utf-8');

      const settings = {
        language: 'en',
        addDistinct: true,
        limit: -1,
        ...(fs.existsSync(settingsPath) ? JSON.parse(fs.readFileSync(settingsPath, 'utf-8')) : {}),
      } as any;

      const specProvider = await buildSpecProviderFromConfig(configTtl, settings.language);

      const translator = new JsonV13SparqlTranslator(specProvider, settings);
      const selectQuery = translator.generateQuery(queryJson);
      const generatedRaw = generator.generate(selectQuery);

      // Normalize the expected using Traqula to avoid formatting diffs
      const expected = generator.generate(parser.parse(expectedRaw)).trim();

      // Normalize the generated by parsing and re-generating as well,
      // so formatting like ';' vs '.' is aligned with Traqula defaults
      const generated = generator.generate(parser.parse(generatedRaw)).trim();

      if (generated !== expected) {
        // Print both queries to ease debugging when the assertion fails
        /* eslint-disable no-console */
        console.log(`\n===== GENERATED (${label}) =====\n${generated}\n`);
        console.log(`===== EXPECTED (${label}) =====\n${expected}\n`);
        /* eslint-enable no-console */
      }
      expect(generated).toBe(expected);
    });
  }
});
