import * as fs from 'fs';
import * as path from 'path';
import { Parser, Generator, SelectQuery } from 'sparqljs';
import { JsonV13SparqlTranslator } from '../../sparnatural/generators/sparql/fromjsonv13/JsonV13SparqlTranslator';
import { SparnaturalQuery } from '../../sparnatural/SparnaturalQueryIfc-v13';
import { SparnaturalSpecificationFactory } from '../../sparnatural/spec-providers/SparnaturalSpecificationFactory';

async function buildSpecProviderFromConfig(configTtl: string, language = 'en') {
  const factory = new SparnaturalSpecificationFactory();
  return await new Promise<any>((resolve, reject) => {
    try {
      factory.build(configTtl, language, undefined, (provider: any) => resolve(provider));
    } catch (e) {
      reject(e);
    }
  });
}

function loadTestCases(baseDir: string) {
  const entries = fs.readdirSync(baseDir, { withFileTypes: true });
  return entries
    .filter((e) => e.isDirectory())
    .map((dir) => path.join(baseDir, dir.name));
}

describe('JsonV13SparqlTranslator directory-driven tests', () => {
  const baseDir = path.join(__dirname, 'cases');
  const generator = new Generator();
  const parser = new Parser();

  if (!fs.existsSync(baseDir)) {
    it('has a cases directory', () => {
      expect(fs.existsSync(baseDir)).toBe(true);
    });
    return;
  }

  const caseDirs = loadTestCases(baseDir);

  if (caseDirs.length === 0) {
    it('has at least one test case directory', () => {
      expect(caseDirs.length).toBeGreaterThan(0);
    });
    return;
  }

  for (const casedir of caseDirs) {
    const label = path.basename(casedir);

    it(`translates case: ${label}`, async () => {
      const queryPath = path.join(casedir, 'query.json');
      const configPath = path.join(casedir, 'config.ttl');
      const expectedPath = path.join(casedir, 'expected.rq');

      expect(fs.existsSync(queryPath)).toBe(true);
      expect(fs.existsSync(configPath)).toBe(true);
      expect(fs.existsSync(expectedPath)).toBe(true);

      const queryJson = JSON.parse(fs.readFileSync(queryPath, 'utf-8')) as SparnaturalQuery;
      const configTtl = fs.readFileSync(configPath, 'utf-8');
      const expectedRaw = fs.readFileSync(expectedPath, 'utf-8');

      const specProvider = await buildSpecProviderFromConfig(configTtl, 'en');

      const settings = { language: 'en', addDistinct: true, limit: -1 } as any;
      const translator = new JsonV13SparqlTranslator(specProvider, settings);
      const selectQuery = translator.generateQuery(queryJson) as SelectQuery;
      const generatedRaw = generator.stringify(selectQuery).trim();

      // Normalize the expected using sparqljs to avoid formatting diffs
      const expectedQuery = parser.parse(expectedRaw) as SelectQuery;
      const expected = generator.stringify(expectedQuery).trim();

      // Normalize the generated by parsing and re-stringifying as well,
      // so formatting like ';' vs '.' is aligned with sparqljs defaults
      const generatedParsed = parser.parse(generatedRaw) as SelectQuery;
      const generated = generator.stringify(generatedParsed).trim();

      if (generated !== expected) {
        // Print both queries to ease debugging when the assertion fails
        /* eslint-disable no-console */
        console.log(`\n===== GENERATED (${label}) =====\n${generated}\n`);
        console.log(`===== EXPECTED (${label}) =====\n${expected}\n`);
        /* eslint-enable no-console */
      }
      expect(generated).toBe(expected);
    });
  }
});
