SELECT DISTINCT ?Person_1 WHERE {
  ?Person_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.
  ?Person_1 <http://example.com/Person_birthDate> ?Date_1.
  FILTER(?Date_1 <= "1950-12-31T23:59:59Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>)
}
