SELECT DISTINCT ?Country_1 ?Continent_1 ?Country_1_label ?Continent_1_label WHERE {
  ?Country_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Country>.
  ?Country_1 <http://example.com/Country_label> ?Country_1_label.
  ?Country_1 <http://example.com/Country_continent> ?Continent_1.
  ?Continent_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Continent>.
  ?Continent_1 <http://example.com/Continent_name> ?Continent_1_label.
}
