var SPARNATURAL_CONFIG_CORE 			=		"http://data.sparna.fr/ontologies/sparnatural-config-core#";

module.exports = Object.freeze({
    SPARNATURAL_CONFIG_CORE			: 		SPARNATURAL_CONFIG_CORE,
	LIST_PROPERTY 					: 		SPARNATURAL_CONFIG_CORE+'ListProperty',
	TIME_PROPERTY_PERIOD 			: 		SPARNATURAL_CONFIG_CORE+'TimeProperty-Period',
	TIME_PROPERTY_YEAR				: 		SPARNATURAL_CONFIG_CORE+'TimeProperty-Year',
	TIME_PROPERTY_DATE			 	: 		SPARNATURAL_CONFIG_CORE+'TimeProperty-Date',
	AUTOCOMPLETE_PROPERTY 			: 		SPARNATURAL_CONFIG_CORE+'AutocompleteProperty',
	SEARCH_PROPERTY 				: 		SPARNATURAL_CONFIG_CORE+'SearchProperty',
	NON_SELECTABLE_PROPERTY 		: 		SPARNATURAL_CONFIG_CORE+'NonSelectableProperty',

	SPARQL_STRING			 		: 		SPARNATURAL_CONFIG_CORE+'sparqlString',
	ICON					 		: 		SPARNATURAL_CONFIG_CORE+'icon',
	FA_ICON					 		: 		SPARNATURAL_CONFIG_CORE+'faIcon',
	HIGHLIGHTED_ICON		 		: 		SPARNATURAL_CONFIG_CORE+'highlightedIcon',

	SPARNATURAL_CLASS				: 		SPARNATURAL_CONFIG_CORE+'SparnaturalClass',
	LINKED_DATA_CLASS				: 		SPARNATURAL_CONFIG_CORE+'LinkedDataClass'
});