SELECT DISTINCT ?Person_1 ?Date_1_begin WHERE {
  ?Person_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/Person>.
  ?Person_1 <http://example.com/Person_beginOnly> ?Date_1.
}
